# Drosera Mainnet Configuration
ethereum_rpc = "https://eth-mainnet.g.alchemy.com/v2/cpHu1Y3S6VhOqPNkh0qKI"
drosera_rpc = "https://relay.ethereum.drosera.io/"

[traps.whale_surge_detector]
path = "out/WhaleTrap.sol/WhaleTrap.json"

# AlertVault contract (mainnet)
response_contract = "0xA7712c4551baE88ab2074812dBE7F64DD9EAa991"
response_function = "alert(bytes32,address,uint8,uint256)"

cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 1

private_trap = true
whitelist = ["0xc93bf33438c9c636fc49cafe1086c2c424507a15"]
address = "0xC4ca71c6bbB98a35098E6345d8682847fc815Fce"
